# Phase 3: Model Training

## Objective

In this phase, we train machine learning models to forecast daily sales quantity for each SKU.

The workflow includes:

- Train/Test Split
- Baseline Model (Random Forest)
- LightGBM Model
- Hyperparameter Tuning with Optuna
- Model Evaluation
- Save Trained Model

In [1]:
import warnings
warnings.filterwarnings("ignore")

import pickle

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

# Machine Learning
from sklearn.ensemble import RandomForestRegressor
import lightgbm as lgbm

# Evaluation Metrics
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

In [2]:
import sys
sys.path.append("../")

from src.utils.utils import weighted_absolute_percentage_error

In [3]:
data = pd.read_csv(
    "../data/processed/data_engineered.csv",
    parse_dates=["shipped_date"]
)

data.head()

,shipped_date,sku,channel,qty,revenue,COGS,MOQ_orders,month,day,dayofweek,...,mean_qty_sku_dow,mean_qty_sku_month,qty_log,lag1,lag7,lag30,rolling_mean_7,rolling_mean_30,rolling_std_7,rolling_std_30
0,2021-01-03,017SAD,ADS,75,3358.95,1660.05,1425,1,3,6,...,0.0,0.0,4.330733,NaN,NaN,NaN,75.0,75.0,NaN,NaN
1,2021-01-15,017SAD,ADS,75,3358.95,1660.05,1425,1,15,4,...,75.0,75.0,4.330733,75.0,NaN,NaN,75.0,75.0,0.0,0.0
2,2021-02-16,017SAD,ADS,75,3358.95,1660.05,1425,2,16,1,...,75.0,75.0,4.330733,75.0,NaN,NaN,75.0,75.0,0.0,0.0
3,2021-02-16,017SAD,LAL,75,2310.00,2009.70,1425,2,16,1,...,75.0,75.0,4.330733,75.0,NaN,NaN,75.0,75.0,0.0,0.0
4,2021-02-26,017SAD,ADS,75,3358.95,1660.05,1425,2,26,4,...,75.0,75.0,4.330733,75.0,NaN,NaN,75.0,75.0,0.0,0.0

In [4]:
data.info()
print(data.shape)

<class 'pandas.DataFrame'>
RangeIndex: 48345 entries, 0 to 48344
Data columns (total 26 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   shipped_date        48345 non-null  datetime64[us]
 1   sku                 48345 non-null  str
 2   channel             48345 non-null  str
 3   qty                 48345 non-null  int64
 4   revenue             48345 non-null  float64
 5   COGS                48345 non-null  float64
 6   MOQ_orders          48345 non-null  int64
 7   month               48345 non-null  int64
 8   day                 48345 non-null  int64
 9   dayofweek           48345 non-null  int64
 10  weekofyear          48345 non-null  int64
 11  quarter             48345 non-null  int64
 12  is_weekend          48345 non-null  int64
 13  is_even_day         48345 non-null  int64
 14  is_holiday          48345 non-null  int64
 15  dow                 48345 non-null  int64
 16  mean_qty_sku_dow    48345 non-null  float64
 17  mean_qty_sku_month  48345 non-null  float64
 18  qty_log             48345 non-null  float64
 19  lag1                47669 non-null  float64
 20  lag7                44633 non-null  float64
 21  lag30               35784 non-null  float64
 22  rolling_mean_7      48345 non-null  float64
 23  rolling_mean_30     48345 non-null  float64
 24  rolling_std_7       47669 non-null  float64
 25  rolling_std_30      47669 non-null  float64
dtypes: datetime64[us](1), float64(12), int64(11), str(2)
memory usage: 9.6 MB
(48345, 26)

## Train-Test Split

Since this is a forecasting problem, the dataset is split chronologically instead of randomly.

In [5]:
data_model = data.sort_values("shipped_date")

split_idx = int(len(data_model) * 0.8)

train = data_model.iloc[:split_idx]

test = data_model.iloc[split_idx:]

print(train.shape)

print(test.shape)

(38676, 26)
(9669, 26)

In [6]:
X_train = train.drop(columns=["qty_log"])
y_train = train["qty_log"]

X_test = test.drop(columns=["qty_log"])
y_test = test["qty_log"]

In [11]:
drop_cols = [
    "qty",
    "shipped_date",
    "sku",
    "revenue",
    "COGS",
    "channel",
    "MOQ_orders"
]

X_train = X_train.drop(columns=drop_cols)

X_test = X_test.drop(columns=drop_cols)

KeyError: "['qty', 'shipped_date', 'sku', 'revenue', 'COGS'] not found in axis"

In [12]:
X_train = X_train.drop(columns=["channel", "MOQ_orders"])
X_test = X_test.drop(columns=["channel", "MOQ_orders"])

In [8]:
print(X_train.shape)
print(X_test.shape)

X_train.head()

(38676, 20)
(9669, 20)

,channel,MOQ_orders,month,day,dayofweek,weekofyear,quarter,is_weekend,is_even_day,is_holiday,dow,mean_qty_sku_dow,mean_qty_sku_month,lag1,lag7,lag30,rolling_mean_7,rolling_mean_30,rolling_std_7,rolling_std_30
27860,ADS,31521,1,1,4,53,1,0,0,1,4,0.0,0.0,NaN,NaN,NaN,57.0,57.0,NaN,NaN
19816,LAL,54080,1,1,4,53,1,0,0,1,4,455.0,455.0,455.0,NaN,NaN,260.0,260.0,275.771645,275.771645
47743,ADS,83844,1,1,4,53,1,0,0,1,4,0.0,0.0,NaN,NaN,NaN,306.0,306.0,NaN,NaN
27540,ADS,27897,1,1,4,53,1,0,0,1,4,68.0,68.0,68.0,NaN,NaN,59.5,59.5,12.020815,12.020815
27539,AWH,27897,1,1,4,53,1,0,0,1,4,0.0,0.0,NaN,NaN,NaN,68.0,68.0,NaN,NaN

## Baseline Model: Random Forest

Before training the final LightGBM model, a Random Forest Regressor is used as a baseline model to evaluate forecasting performance.

This provides a benchmark for comparing more advanced models.

### Train Random Forest

In [13]:
rf_model = RandomForestRegressor(
    n_estimators=100,
    random_state=42,
    n_jobs=-1
)

rf_model.fit(X_train, y_train)

RandomForestRegressor(n_jobs=-1, random_state=42)

### Prediction

In [14]:
rf_pred_log = rf_model.predict(X_test)

rf_pred = np.expm1(rf_pred_log)

actual = np.expm1(y_test)

### Evaluation

In [15]:
rf_mae = mean_absolute_error(actual, rf_pred)

rf_rmse = np.sqrt(
    mean_squared_error(actual, rf_pred)
)

rf_r2 = r2_score(actual, rf_pred)

rf_wape = weighted_absolute_percentage_error(
    actual,
    rf_pred
)

In [16]:
print("=" * 50)
print("Random Forest Performance")
print("=" * 50)

print(f"MAE  : {rf_mae:.2f}")
print(f"RMSE : {rf_rmse:.2f}")
print(f"R²   : {rf_r2:.4f}")
print(f"WAPE : {rf_wape:.2f}%")

==================================================
Random Forest Performance
==================================================
MAE  : 115.64
RMSE : 224.44
R²   : 0.5458
WAPE : 49.83%

### Baseline Model Performance

The Random Forest model serves as a baseline for comparison.

Although it captures part of the sales pattern (R² ≈ 0.55), the prediction error remains relatively high (WAPE ≈ 50%), indicating room for improvement.

In the next section, LightGBM will be trained to improve forecasting performance.

### Time Series Cross Validation

In [18]:
import optuna

In [20]:
from sklearn.model_selection import TimeSeriesSplit

In [21]:
tscv = TimeSeriesSplit(n_splits=5)

for fold, (train_idx, valid_idx) in enumerate(tscv.split(X_train)):
    print(
        f"Fold {fold+1}: "
        f"Train={len(train_idx)}, "
        f"Validation={len(valid_idx)}"
    )

Fold 1: Train=6446, Validation=6446
Fold 2: Train=12892, Validation=6446
Fold 3: Train=19338, Validation=6446
Fold 4: Train=25784, Validation=6446
Fold 5: Train=32230, Validation=6446

In [22]:
def objective(trial):

    params = {
        "objective": "regression",
        "metric": "rmse",
        "verbosity": -1,
        "boosting_type": "gbdt",
        "random_state": 42,

        "learning_rate": trial.suggest_float(
            "learning_rate",
            0.01,
            0.2
        ),

        "num_leaves": trial.suggest_int(
            "num_leaves",
            20,
            100
        ),

        "max_depth": trial.suggest_int(
            "max_depth",
            3,
            12
        ),

        "min_child_samples": trial.suggest_int(
            "min_child_samples",
            5,
            50
        ),

        "subsample": trial.suggest_float(
            "subsample",
            0.6,
            1.0
        ),

        "colsample_bytree": trial.suggest_float(
            "colsample_bytree",
            0.6,
            1.0
        ),

        "n_estimators": 500
    }

    rmse_scores = []

    for train_idx, valid_idx in tscv.split(X_train):

        X_tr = X_train.iloc[train_idx]
        X_val = X_train.iloc[valid_idx]

        y_tr = y_train.iloc[train_idx]
        y_val = y_train.iloc[valid_idx]

        model = lgbm.LGBMRegressor(**params)

        model.fit(X_tr, y_tr)

        pred = model.predict(X_val)

        rmse = np.sqrt(
            mean_squared_error(
                y_val,
                pred
            )
        )

        rmse_scores.append(rmse)

    return np.mean(rmse_scores)

### Study

In [23]:
study = optuna.create_study(
    direction="minimize",
    study_name="lightgbm_sales_forecasting"
)

[I 2026-07-08 14:18:21,984] A new study created in memory with name: lightgbm_sales_forecasting

In [24]:
study.optimize(
    objective,
    n_trials=20,
    show_progress_bar=True
)

  0%|          | 0/20 [00:00<?, ?it/s]

[I 2026-07-08 14:18:39,113] Trial 0 finished with value: 0.6487984284452335 and parameters: {'learning_rate': 0.09447164286340702, 'num_leaves': 85, 'max_depth': 3, 'min_child_samples': 45, 'subsample': 0.9297419280122075, 'colsample_bytree': 0.8264268401300149}. Best is trial 0 with value: 0.6487984284452335.
[I 2026-07-08 14:18:47,789] Trial 1 finished with value: 0.6493167667057654 and parameters: {'learning_rate': 0.06357678207832207, 'num_leaves': 86, 'max_depth': 6, 'min_child_samples': 37, 'subsample': 0.7379399819490513, 'colsample_bytree': 0.6261016932482658}. Best is trial 0 with value: 0.6487984284452335.
[I 2026-07-08 14:18:56,915] Trial 2 finished with value: 0.6582076063985174 and parameters: {'learning_rate': 0.10451947837400373, 'num_leaves': 36, 'max_depth': 8, 'min_child_samples': 34, 'subsample': 0.6880238966853982, 'colsample_bytree': 0.91950752980603}. Best is trial 0 with value: 0.6487984284452335.
[I 2026-07-08 14:19:11,588] Trial 3 finished with value: 0.6535538938220498 and parameters: {'learning_rate': 0.07192245206014025, 'num_leaves': 66, 'max_depth': 12, 'min_child_samples': 49, 'subsample': 0.901963756197573, 'colsample_bytree': 0.982663195851985}. Best is trial 0 with value: 0.6487984284452335.
[I 2026-07-08 14:19:13,915] Trial 4 finished with value: 0.650416656743014 and parameters: {'learning_rate': 0.1575811081693536, 'num_leaves': 68, 'max_depth': 3, 'min_child_samples': 50, 'subsample': 0.9674236855556977, 'colsample_bytree': 0.925503696729389}. Best is trial 0 with value: 0.6487984284452335.
[I 2026-07-08 14:19:17,772] Trial 5 finished with value: 0.6487785948258917 and parameters: {'learning_rate': 0.05404988529805454, 'num_leaves': 94, 'max_depth': 4, 'min_child_samples': 43, 'subsample': 0.6259487453528078, 'colsample_bytree': 0.6445906841349507}. Best is trial 5 with value: 0.6487785948258917.
[I 2026-07-08 14:19:23,688] Trial 6 finished with value: 0.6749398521404337 and parameters: {'learning_rate': 0.17385171576435507, 'num_leaves': 88, 'max_depth': 5, 'min_child_samples': 20, 'subsample': 0.8125169799479921, 'colsample_bytree': 0.8632507145342921}. Best is trial 5 with value: 0.6487785948258917.
[I 2026-07-08 14:19:27,373] Trial 7 finished with value: 0.6640547408426057 and parameters: {'learning_rate': 0.18914389632716852, 'num_leaves': 86, 'max_depth': 4, 'min_child_samples': 26, 'subsample': 0.8606885271430189, 'colsample_bytree': 0.8390319769070691}. Best is trial 5 with value: 0.6487785948258917.
[I 2026-07-08 14:19:37,775] Trial 8 finished with value: 0.6837176225005596 and parameters: {'learning_rate': 0.19232711551897727, 'num_leaves': 37, 'max_depth': 8, 'min_child_samples': 6, 'subsample': 0.8081659940646406, 'colsample_bytree': 0.7765223551286647}. Best is trial 5 with value: 0.6487785948258917.
[I 2026-07-08 14:19:41,624] Trial 9 finished with value: 0.6586129442560298 and parameters: {'learning_rate': 0.12440539798619933, 'num_leaves': 54, 'max_depth': 4, 'min_child_samples': 17, 'subsample': 0.8646533872422546, 'colsample_bytree': 0.7099155354343025}. Best is trial 5 with value: 0.6487785948258917.
[I 2026-07-08 14:19:51,810] Trial 10 finished with value: 0.6487903702968593 and parameters: {'learning_rate': 0.018051733387885315, 'num_leaves': 28, 'max_depth': 12, 'min_child_samples': 5, 'subsample': 0.6276439188905352, 'colsample_bytree': 0.6091585940962032}. Best is trial 5 with value: 0.6487785948258917.
[I 2026-07-08 14:20:00,631] Trial 11 finished with value: 0.6494285543355283 and parameters: {'learning_rate': 0.017291586342071428, 'num_leaves': 24, 'max_depth': 12, 'min_child_samples': 5, 'subsample': 0.6142701702473288, 'colsample_bytree': 0.600027936228735}. Best is trial 5 with value: 0.6487785948258917.
[I 2026-07-08 14:20:28,606] Trial 12 finished with value: 0.6452545099055398 and parameters: {'learning_rate': 0.011183019923959717, 'num_leaves': 100, 'max_depth': 9, 'min_child_samples': 16, 'subsample': 0.602599020110538, 'colsample_bytree': 0.6810744771653895}. Best is trial 12 with value: 0.6452545099055398.
[I 2026-07-08 14:20:47,196] Trial 13 finished with value: 0.649637275865579 and parameters: {'learning_rate': 0.05056175729048039, 'num_leaves': 100, 'max_depth': 10, 'min_child_samples': 36, 'subsample': 0.6782113535469836, 'colsample_bytree': 0.6933781894163661}. Best is trial 12 with value: 0.6452545099055398.
[I 2026-07-08 14:21:03,181] Trial 14 finished with value: 0.6486421868165209 and parameters: {'learning_rate': 0.03651801064484604, 'num_leaves': 98, 'max_depth': 7, 'min_child_samples': 15, 'subsample': 0.6003364074595887, 'colsample_bytree': 0.6892251075373731}. Best is trial 12 with value: 0.6452545099055398.
[I 2026-07-08 14:21:20,797] Trial 15 finished with value: 0.6475146113798131 and parameters: {'learning_rate': 0.03426035803794026, 'num_leaves': 74, 'max_depth': 8, 'min_child_samples': 14, 'subsample': 0.6885141369658975, 'colsample_bytree': 0.7244715519227594}. Best is trial 12 with value: 0.6452545099055398.
[I 2026-07-08 14:21:42,757] Trial 16 finished with value: 0.6446707905372124 and parameters: {'learning_rate': 0.012296339795760456, 'num_leaves': 72, 'max_depth': 10, 'min_child_samples': 12, 'subsample': 0.7251060339193578, 'colsample_bytree': 0.7453592679149353}. Best is trial 16 with value: 0.6446707905372124.
[I 2026-07-08 14:21:59,403] Trial 17 finished with value: 0.6437659104349172 and parameters: {'learning_rate': 0.011952027720200693, 'num_leaves': 53, 'max_depth': 10, 'min_child_samples': 23, 'subsample': 0.7568488016940612, 'colsample_bytree': 0.7801361637964015}. Best is trial 17 with value: 0.6437659104349172.
[I 2026-07-08 14:22:14,263] Trial 18 finished with value: 0.6468429183900531 and parameters: {'learning_rate': 0.03640390057395343, 'num_leaves': 55, 'max_depth': 10, 'min_child_samples': 25, 'subsample': 0.7554257777152853, 'colsample_bytree': 0.77606884882025}. Best is trial 17 with value: 0.6437659104349172.
[I 2026-07-08 14:22:28,093] Trial 19 finished with value: 0.6600242615970497 and parameters: {'learning_rate': 0.08349019005846842, 'num_leaves': 49, 'max_depth': 10, 'min_child_samples': 11, 'subsample': 0.7541373443481288, 'colsample_bytree': 0.7681799698176305}. Best is trial 17 with value: 0.6437659104349172.

In [25]:
print("Best RMSE:")
print(study.best_value)

print("\nBest Parameters:")
print(study.best_params)

Best RMSE:
0.6437659104349172

Best Parameters:
{'learning_rate': 0.011952027720200693, 'num_leaves': 53, 'max_depth': 10, 'min_child_samples': 23, 'subsample': 0.7568488016940612, 'colsample_bytree': 0.7801361637964015}

In [26]:
best_params = study.best_params

best_params

{'learning_rate': 0.011952027720200693,
 'num_leaves': 53,
 'max_depth': 10,
 'min_child_samples': 23,
 'subsample': 0.7568488016940612,
 'colsample_bytree': 0.7801361637964015}

In [33]:
best_params.update({
    "objective": "regression",
    "metric": "rmse",
    "random_state": 42,
    "verbosity": -1,
    "n_estimators": 500
})

In [34]:
final_model = lgbm.LGBMRegressor(
    **best_params
)

final_model.fit(
    X_train,
    y_train
)

LGBMRegressor(colsample_bytree=0.7801361637964015,
              learning_rate=0.011952027720200693, max_depth=10, metric='rmse',
              min_child_samples=23, n_estimators=500, num_leaves=53,
              objective='regression', random_state=42,
              subsample=0.7568488016940612, verbosity=-1)

In [35]:
pred_log = final_model.predict(X_test)

prediction = np.expm1(pred_log)

actual = np.expm1(y_test)

In [36]:
lgb_mae = mean_absolute_error(actual, prediction)

lgb_rmse = np.sqrt(
    mean_squared_error(actual, prediction)
)

lgb_r2 = r2_score(actual, prediction)

lgb_wape = weighted_absolute_percentage_error(
    actual,
    prediction
)

In [37]:
comparison = pd.DataFrame({
    "Model": ["Random Forest", "LightGBM"],
    "MAE": [rf_mae, lgb_mae],
    "RMSE": [rf_rmse, lgb_rmse],
    "R2": [rf_r2, lgb_r2],
    "WAPE": [rf_wape, lgb_wape]
})

comparison

           Model         MAE        RMSE        R2       WAPE
0  Random Forest  115.644108  224.444922  0.545837  49.825053
1       LightGBM  111.801616  216.350784  0.578003  48.169522

### Model Comparison

LightGBM achieved better forecasting performance than the Random Forest baseline across all evaluation metrics.

Compared with Random Forest:

- MAE decreased from **115.64** to **111.80**
- RMSE decreased from **224.44** to **216.35**
- R² improved from **0.546** to **0.578**
- WAPE decreased from **49.83%** to **48.17%**

Therefore, the optimized LightGBM model was selected as the final forecasting model.

In [38]:
import pickle
import os

os.makedirs("../models", exist_ok=True)

with open("../models/sales_forecast_model.pkl", "wb") as f:
    pickle.dump(final_model, f)

print("Model saved successfully!")

Model saved successfully!

In [39]:
import os

os.listdir("../models")

['sales_forecast_model.pkl']